import { NextRequest, NextResponse } from "next/server";
import JSZip from 'jszip';
import path from 'path';

export async function POST(req: NextRequest) {
  const { deliverable } = await req.json();

  try {
    // Generate file based on deliverable type
    let fileContent: Uint8Array;
    let contentType: string;
    let filename: string;

    switch (deliverable.type) {
      case "presentation":
        fileContent = await generatePresentation(deliverable);
        contentType = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
        filename = `${deliverable.name}.pptx`;
        break;
      
      case "pdf":
        fileContent = await generatePDF(deliverable);
        contentType = "application/pdf";
        filename = `${deliverable.name}.pdf`;
        break;
      
      case "codebase":
        fileContent = await generateCodebaseZip(deliverable);
        contentType = "application/zip";
        filename = `${deliverable.name}.zip`;
        break;
      
      case "image":
        fileContent = await generateImage(deliverable);
        contentType = "image/png";
        filename = `${deliverable.name}.png`;
        break;
      
      case "document":
        fileContent = await generateDocument(deliverable);
        contentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
        filename = `${deliverable.name}.docx`;
        break;
      
      case "spreadsheet":
        fileContent = await generateSpreadsheet(deliverable);
        contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        filename = `${deliverable.name}.xlsx`;
        break;
      
      default:
        throw new Error("Unsupported deliverable type");
    }

    // Create file response
    return new NextResponse(Buffer.from(fileContent), {
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': fileContent.length.toString(),
      },
    });
  } catch (error) {
    console.error('File generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate file' },
      { status: 500 }
    );
  }
}

async function generatePresentation(deliverable: any): Promise<Uint8Array> {
  const pptxgen = (await import("pptxgenjs")).default;
  const pres = new pptxgen();
  
  // Default styling (16:9)
  pres.layout = "LAYOUT_16x9";
  
  // Master Slide
  pres.defineSlideMaster({
    title: "MASTER_SLIDE",
    background: { color: "0F172A" },
    objects: [
      { rect: { x: 0, y: 0, w: "100%", h: 0.1, fill: { color: "00EEFF" } } },
      { text: { text: "HEDERON AI", options: { x: 8.5, y: 5.2, w: 1.5, fontSize: 10, color: "475569", align: "right" } } }
    ]
  });

  // Title Slide
  const slide1 = pres.addSlide({ masterName: "MASTER_SLIDE" });
  slide1.addText(deliverable.name, {
    x: 1, y: 1.8, w: 8, h: 1.5,
    fontSize: 44, color: "FFFFFF", align: "left", bold: true,
    fontFace: "Arial"
  });
  slide1.addText("Generated by Hederon AI Autonomous Agent Swarm", {
    x: 1, y: 3.5, w: 8, h: 0.5,
    fontSize: 16, color: "94A3B8", align: "left"
  });
  
  // Content Slide
  const slide2 = pres.addSlide({ masterName: "MASTER_SLIDE" });
  slide2.addText("Executive Overview", {
    x: 0.5, y: 0.5, w: 9, h: 0.5,
    fontSize: 24, color: "00EEFF", bold: true,
    fontFace: "Arial"
  });
  
  const contentText = deliverable.content || "";
  const lines = contentText.split('\\n').filter((l: string) => l.trim().length > 0)
    .map((line: string) => {
      const isBullet = line.trim().startsWith('-') || line.trim().startsWith('*');
      return {
        text: line.replace(/^[-*#\\s]+/, '').trim(),
        options: { 
          bullet: isBullet, 
          color: "F8FAFC", 
          fontSize: 14, 
          fontFace: "Arial",
          breakLine: true,
          indentLevel: isBullet ? 1 : 0
        }
      };
    });
    
  slide2.addText(lines.slice(0, 10) as any, { 
    x: 0.5, y: 1.2, w: 9, h: 4,
    valign: "top", align: "left"
  });

  const data = await pres.write({ outputType: "uint8array" }) as Uint8Array;
  return data;
}

async function generatePDF(deliverable: any): Promise<Uint8Array> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // PAGE 1: COVER
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, pageHeight, "F");
  
  doc.setFillColor(0, 238, 255);
  doc.rect(0, 0, pageWidth, 4, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(36);
  doc.setFont("helvetica", "bold");
  
  const titleLines = doc.splitTextToSize(deliverable.name, pageWidth - 40);
  doc.text(titleLines, 20, 100);
  
  doc.setFontSize(14);
  doc.setTextColor(148, 163, 184);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by Hederon AI Autonomous Agent Swarm", 20, 100 + (titleLines.length * 15) + 10);
  
  doc.setFontSize(10);
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 20, pageHeight - 30);
  
  doc.setDrawColor(0, 238, 255);
  doc.setLineWidth(1);
  doc.circle(pageWidth - 30, pageHeight - 32, 8, "S");
  doc.setFontSize(8);
  doc.setTextColor(0, 238, 255);
  doc.text("AI", pageWidth - 32, pageHeight - 30);

  // PAGE 2: CONTENT
  doc.addPage();
  doc.setFillColor(248, 250, 252);
  doc.rect(0, 0, pageWidth, pageHeight, "F");
  
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("EXECUTIVE REPORT", 20, 20);
  
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  
  const contentText = deliverable.content || "";
  const paragraphs = contentText.split('\\n\\n');
  
  let y = 50;
  for (const para of paragraphs) {
    if (para.trim() === "") continue;
    
    if (para.startsWith("##") || para.startsWith("#")) {
       const headerText = para.replace(/#/g, "").trim();
       doc.setFont("helvetica", "bold");
       doc.setFontSize(14);
       doc.setTextColor(15, 23, 42);
       
       if (y > pageHeight - 40) { doc.addPage(); y = 30; }
       doc.text(headerText, 20, y);
       y += 10;
       continue;
    }
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(51, 65, 85);
    
    const lines = doc.splitTextToSize(para, pageWidth - 40);
    if (y + (lines.length * 5) > pageHeight - 20) { doc.addPage(); y = 30; }
    doc.text(lines, 20, y);
    y += (lines.length * 5.5) + 5;
  }
  
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    if (i !== 1) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Hederon AI Generated Artifact  |  Page ${i} of ${totalPages}`, 20, pageHeight - 15);
      doc.setFillColor(0, 238, 255);
      doc.circle(pageWidth - 20, 15, 3, "F");
    }
  }

  const arrayBuffer = doc.output("arraybuffer");
  return new Uint8Array(arrayBuffer);
}

async function generateCodebaseZip(deliverable: any): Promise<Uint8Array> {
  const zip = new JSZip();
  
  // Parse deliverable content to extract files
  const files = parseCodebaseFiles(deliverable);
  
  // Add each file to ZIP
  for (const file of files) {
    zip.file(file.path, file.content);
  }
  
  // Generate ZIP buffer
  const zipBuffer = await zip.generateAsync({ type: "uint8array" });
  return zipBuffer;
}

function parseCodebaseFiles(deliverable: any): Array<{path: string, content: string}> {
  const files = [];
  
  // Default file structure for codebase
  files.push({
    path: "README.md",
    content: `# ${deliverable.name}\n\nGenerated by Hederon AI\n\n${deliverable.content}`
  });
  
  files.push({
    path: "package.json",
    content: JSON.stringify({
      name: deliverable.name.toLowerCase().replace(/\s+/g, '-'),
      version: "1.0.0",
      description: `Generated by Hederon AI: ${deliverable.name}`,
      main: "index.js",
      scripts: {
        start: "node index.js",
        dev: "node index.js"
      },
      dependencies: {
        express: "^4.18.0",
        cors: "^2.8.5"
      }
    }, null, 2)
  });
  
  files.push({
    path: "index.js",
    content: `// Main entry point - Generated by Hederon AI
const express = require('express');
const cors = require('cors');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// Routes
app.get('/', (req, res) => {
  res.json({ 
    message: '${deliverable.name}',
    description: 'Generated by Hederon AI',
    timestamp: new Date().toISOString()
  });
});

// Start server
app.listen(PORT, () => {
  console.log(\`${deliverable.name} running on port \${PORT}\`);
});`
  });
  
  files.push({
    path: ".env.example",
    content: `# Environment variables for ${deliverable.name}
PORT=3000
NODE_ENV=development`
  });
  
  return files;
}

async function generateImage(deliverable: any): Promise<Uint8Array> {
  // Enhanced SVG to PNG conversion (simplified)
  const svgContent = `<svg width="1200" height="800" xmlns="http://www.w3.org/2000/svg">
    <defs>
      <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" style="stop-color:#667eea;stop-opacity:1" />
        <stop offset="100%" style="stop-color:#764ba2;stop-opacity:1" />
      </linearGradient>
    </defs>
    <rect width="1200" height="800" fill="url(#grad1)"/>
    <text x="600" y="400" text-anchor="middle" font-family="Arial, sans-serif" font-size="32" fill="white" font-weight="bold">
      ${deliverable.name}
    </text>
    <text x="600" y="450" text-anchor="middle" font-family="Arial, sans-serif" font-size="18" fill="white">
      Generated by Hederon AI
    </text>
  </svg>`;
  
  return new TextEncoder().encode(svgContent);
}

async function generateDocument(deliverable: any): Promise<Uint8Array> {
  // Enhanced DOCX generation
  const docxContent = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:wordDocument xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Title"/>
      </w:pPr>
      <w:r>
        <w:t>${deliverable.name}</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r>
        <w:t>${deliverable.content}</w:t>
      </w:r>
    </w:p>
  </w:body>
</w:wordDocument>`;
  
  return new TextEncoder().encode(docxContent);
}

async function generateSpreadsheet(deliverable: any): Promise<Uint8Array> {
  // Enhanced XLSX generation
  const xlsxContent = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <sheetData>
    <row>
      <c>
        <v>${deliverable.name}</v>
      </c>
    </row>
    <row>
      <c>
        <v>${deliverable.content}</v>
      </c>
    </row>
  </sheetData>
</worksheet>`;
  
  return new TextEncoder().encode(xlsxContent);
}
