import { NextRequest, NextResponse } from "next/server";
import JSZip from 'jszip';
import { uploadToIPFS, uploadDirectoryToIPFS } from '@/lib/ipfs';

export async function POST(req: NextRequest) {
  const { deliverable } = await req.json();

  try {
    // Generate file based on deliverable type
    let fileContent: Uint8Array;
    let contentType: string;
    let filename: string;

    switch (deliverable.type) {
      case "presentation":
        fileContent = await generatePresentation(deliverable);
        contentType = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
        filename = `${deliverable.name}.pptx`;
        break;
      
      case "pdf":
        fileContent = await generatePDF(deliverable);
        contentType = "application/pdf";
        filename = `${deliverable.name}.pdf`;
        break;
      
      case "codebase":
        fileContent = await generateCodebaseZip(deliverable);
        contentType = "application/zip";
        filename = `${deliverable.name}.zip`;
        break;
      
      case "image":
        fileContent = await generateImage(deliverable);
        contentType = "image/png";
        filename = `${deliverable.name}.png`;
        break;
      
      case "document":
        fileContent = await generateDocument(deliverable);
        contentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
        filename = `${deliverable.name}.docx`;
        break;
      
      case "spreadsheet":
        fileContent = await generateSpreadsheet(deliverable);
        contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        filename = `${deliverable.name}.xlsx`;
        break;
      
      default:
        throw new Error("Unsupported deliverable type");
    }

    const appUrl = req.nextUrl.origin;
    
    // Auth context for User/Project isolation
    const { auth } = await import("@/auth");
    const session = await auth();
    const userId = session?.user?.id || session?.user?.email || "anonymous_user";
    const projectId = deliverable.id || deliverable.name || "unnamed_project";
    
    // Sanitize ID strings for filesystem use
    const sanitizePath = (str: string) => str.replace(/[^a-zA-Z0-9_-]/g, "_").substring(0, 40);
    const orgPath = `${sanitizePath(userId)}/${sanitizePath(projectId)}`;

    // Upload to IPFS for decentralized storage
    let ipfsResult;
    if (deliverable.type === "codebase") {
      // For codebases, upload as directory
      const files = parseCodebaseFiles(deliverable.content, deliverable.name);
      ipfsResult = await uploadDirectoryToIPFS(files, deliverable.name, appUrl, orgPath);
    } else {
      // For single files, upload directly
      ipfsResult = await uploadToIPFS(fileContent, filename, contentType, appUrl, orgPath);
    }

    // Return IPFS information
    return NextResponse.json({
      success: true,
      ipfsHash: ipfsResult.hash,
      ipfsUrl: ipfsResult.url,
      filename: filename,
      size: ipfsResult.size,
      contentType: contentType,
      gatewayUrl: ipfsResult.url,
      message: `File successfully ${ipfsResult.url.includes('api/ipfs') ? 'emulated locally' : 'uploaded to IPFS'} and pinned for persistence`
    });

  } catch (error) {
    console.error('IPFS file generation error:', error);
    return NextResponse.json(
      { 
        success: false,
        error: 'Failed to generate and upload file to IPFS: ' + (error as Error).message
      },
      { status: 500 }
    );
  }
}

// ---- Real Library Based Generation (Using Dynamic Imports to fix Build Errors) ----

async function generatePresentation(deliverable: any): Promise<Uint8Array> {
  const pptxgen = (await import("pptxgenjs")).default;
  const pres = new pptxgen();
  
  // Title Slide
  const slide1 = pres.addSlide();
  slide1.background = { fill: "1A1A1A" };
  slide1.addText(deliverable.name, {
    x: 1, y: 2, w: 8, h: 2,
    fontSize: 44, color: "00EEFF", align: "center", bold: true
  });
  slide1.addText("Generated by ExecuAI Autonomous Agent Swarm", {
    x: 1, y: 4, w: 8, h: 1,
    fontSize: 18, color: "AAAAAA", align: "center"
  });

  // Content Slide
  const slide2 = pres.addSlide();
  slide2.background = { fill: "F5F5F5" };
  slide2.addText(deliverable.name + " - Brief", {
    x: 0.5, y: 0.5, w: 9, h: 1,
    fontSize: 24, color: "333333", bold: true
  });
  
  const content = deliverable.content || "";
  slide2.addText(content.slice(0, 1000), {
    x: 0.5, y: 1.5, w: 9, h: 5,
    fontSize: 14, color: "666666", align: "left", valign: "top"
  });

  // Export as Uint8Array
  const data = await pres.write({ outputType: "uint8array" }) as Uint8Array;
  return data;
}

async function generatePDF(deliverable: any): Promise<Uint8Array> {
  // Use try/catch because jsPDF import triggers fflate which can be picky in Node
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(33, 33, 33);
  doc.rect(0, 0, 210, 40, "F");
  doc.setTextColor(0, 238, 255);
  doc.setFontSize(22);
  doc.text("ExecuAI Project Artifact", 10, 25);
  
  doc.setTextColor(200, 200, 200);
  doc.setFontSize(10);
  doc.text(new Date().toISOString(), 150, 25);

  // Title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.text(deliverable.name, 10, 55);
  
  // Content (Simple auto-pagination logic)
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  const splitText = doc.splitTextToSize(deliverable.content || "", 180);
  doc.text(splitText, 10, 70);

  // Project Scope Charts (Simulated for SDLC)
  if (deliverable.name.toLowerCase().includes("roadmap") || deliverable.name.toLowerCase().includes("plan") || deliverable.name.toLowerCase().includes("architecture")) {
      const startY = 150;
      doc.setFontSize(14);
      doc.text("Project Phase Timeline & Resource Flow", 10, startY - 10);
      
      // Draw a simple Gantt-style chart
      const phases = ["Reqs", "Design", "Dev", "Test", "Deploy"];
      phases.forEach((phase, i) => {
          doc.setFillColor(0, 150, 255 - (i * 30));
          doc.rect(40 + (i * 20), startY + (i * 10), 60 + (i * 5), 8, "F");
          doc.text(phase, 10, startY + (i * 10) + 6);
      });
  }

  const arrayBuffer = doc.output("arraybuffer");
  return new Uint8Array(arrayBuffer);
}

async function generateCodebaseZip(deliverable: any): Promise<Uint8Array> {
  const zip = new JSZip();
  const name = deliverable.name || "project";
  
  // 1. Root Files
  zip.file("README.md", `# ${name}\n\nGenerated by ExecuAI\n\n${deliverable.content}`);
  zip.file("package.json", JSON.stringify({
    name: name.toLowerCase().replace(/\s+/g, '-'),
    version: "1.0.0",
    dependencies: { "express": "^4.18.2", "cors": "^2.8.5" }
  }, null, 2));
  zip.file(".gitignore", "node_modules\n.env\ndist");

  // 2. Source Code
  const src = zip.folder("src");
  src?.file("index.js", `const express = require('express');\nconst app = express();\n\napp.get('/', (req, res) => res.json({ status: 'ok', project: '${name}' }));\n\napp.listen(3000, () => console.log('Server running on 3000'));`);
  
  // 3. SDLC Documents Folder
  const docs = zip.folder("docs");
  docs?.file("REQUIREMENTS.md", `## Requirements for ${name}\n\n1. Initial Launch\n2. User Auth\n3. Scalability`);
  docs?.file("ARCHITECTURE.md", `## Architecture Design\n\n- Frontend: React\n- Backend: Node.js\n- Database: Hedera Managed`);
  docs?.file("TEST_PLAN.md", `## Test Strategy\n\n- Unit Testing\n- Integration Testing\n- User Acceptance`);

  const zipBuffer = await zip.generateAsync({ type: "uint8array" });
  return zipBuffer;
}

// ... helper functions for other types (keeping them simple for brevity but using better headers)
async function generateImage(deliverable: any): Promise<Uint8Array> {
  return new TextEncoder().encode(`<svg width="1200" height="630" viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
    <rect width="1200" height="630" fill="#0A0A0A"/>
    <text x="600" y="300" text-anchor="middle" font-family="Arial" font-size="48" fill="#00EEFF">${deliverable.name}</text>
  </svg>`);
}

async function generateDocument(deliverable: any): Promise<Uint8Array> {
  return new TextEncoder().encode(`<w:wordDocument xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>${deliverable.content}</w:t></w:r></w:p></w:body></w:wordDocument>`);
}

async function generateSpreadsheet(deliverable: any): Promise<Uint8Array> {
  return new TextEncoder().encode(`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row><c><v>Item</v></c><c><v>Quantity</v></c><c><v>Cost</v></c></row><row><c><v>Infrastructure</v></c><c><v>1</v></c><c><v>500</v></c></row></sheetData></worksheet>`);
}

function parseCodebaseFiles(content: string, name: string = "project"): Array<{path: string, content: string | Uint8Array}> {
    return [
        { path: "README.md", content: `# ${name}\n\n${content}` },
        { path: "src/index.js", content: `console.log("Hello from ${name}");` }
    ];
}
