import { NextRequest, NextResponse } from "next/server";
import JSZip from 'jszip';
import { uploadToIPFS, uploadDirectoryToIPFS } from '@/lib/ipfs';

export async function POST(req: NextRequest) {
  const { deliverable } = await req.json();

  try {
    // Generate file based on deliverable type
    let fileContent: Uint8Array;
    let contentType: string;
    let filename: string;

    switch (deliverable.type) {
      case "presentation":
        fileContent = await generatePresentation(deliverable);
        contentType = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
        filename = `${deliverable.name}.pptx`;
        break;
      
      case "pdf":
        fileContent = await generatePDF(deliverable);
        contentType = "application/pdf";
        filename = `${deliverable.name}.pdf`;
        break;
      
      case "codebase":
        fileContent = await generateCodebaseZip(deliverable);
        contentType = "application/zip";
        filename = `${deliverable.name}.zip`;
        break;
      
      case "image":
        fileContent = await generateImage(deliverable);
        contentType = "image/png";
        filename = `${deliverable.name}.png`;
        break;
      
      case "document":
        fileContent = await generateDocument(deliverable);
        contentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
        filename = `${deliverable.name}.docx`;
        break;
      
      case "spreadsheet":
        fileContent = await generateSpreadsheet(deliverable);
        contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        filename = `${deliverable.name}.xlsx`;
        break;
      
      default:
        throw new Error("Unsupported deliverable type");
    }

    const appUrl = req.nextUrl.origin;
    
    // Auth context for User/Project isolation
    const { auth } = await import("@/auth");
    const session = await auth();
    const userId = session?.user?.id || session?.user?.email || "anonymous_user";
    const projectId = deliverable.id || deliverable.name || "unnamed_project";
    
    // Sanitize ID strings for filesystem use
    const sanitizePath = (str: string) => str.replace(/[^a-zA-Z0-9_-]/g, "_").substring(0, 40);
    const orgPath = `${sanitizePath(userId)}/${sanitizePath(projectId)}`;

    // Upload to IPFS for decentralized storage
    let ipfsResult;
    if (deliverable.type === "codebase") {
      // For codebases, upload as directory
      const files = parseCodebaseFiles(deliverable.content, deliverable.name);
      ipfsResult = await uploadDirectoryToIPFS(files, deliverable.name, appUrl, orgPath);
    } else {
      // For single files, upload directly
      ipfsResult = await uploadToIPFS(fileContent, filename, contentType, appUrl, orgPath);
    }

    // Return IPFS information
    return NextResponse.json({
      success: true,
      ipfsHash: ipfsResult.hash,
      ipfsUrl: ipfsResult.url,
      filename: filename,
      size: ipfsResult.size,
      contentType: contentType,
      gatewayUrl: ipfsResult.url,
      message: `File successfully ${ipfsResult.url.includes('api/ipfs') ? 'emulated locally' : 'uploaded to IPFS'} and pinned for persistence`
    });

  } catch (error) {
    console.error('IPFS file generation error:', error);
    return NextResponse.json(
      { 
        success: false,
        error: 'Failed to generate and upload file to IPFS: ' + (error as Error).message
      },
      { status: 500 }
    );
  }
}

// ---- Real Library Based Generation (Using Dynamic Imports to fix Build Errors) ----

async function generatePresentation(deliverable: any): Promise<Uint8Array> {
  const pptxgen = (await import("pptxgenjs")).default;
  const pres = new pptxgen();
  
  // Default styling (16:9)
  pres.layout = "LAYOUT_16x9";
  
  // Master Slide
  pres.defineSlideMaster({
    title: "MASTER_SLIDE",
    background: { color: "0F172A" },
    objects: [
      { rect: { x: 0, y: 0, w: "100%", h: 0.1, fill: { color: "00EEFF" } } },
      { text: { text: "EXECUAI", options: { x: 8.5, y: 5.2, w: 1, fontSize: 10, color: "475569", align: "right" } } }
    ]
  });

  // Title Slide
  const slide1 = pres.addSlide({ masterName: "MASTER_SLIDE" });
  slide1.addText(deliverable.name, {
    x: 1, y: 1.8, w: 8, h: 1.5,
    fontSize: 44, color: "FFFFFF", align: "left", bold: true,
    fontFace: "Arial"
  });
  slide1.addText("Generated by ExecuAI Autonomous Agent Swarm", {
    x: 1, y: 3.5, w: 8, h: 0.5,
    fontSize: 16, color: "94A3B8", align: "left"
  });
  
  // Content Slide
  const slide2 = pres.addSlide({ masterName: "MASTER_SLIDE" });
  slide2.addText("Executive Overview", {
    x: 0.5, y: 0.5, w: 9, h: 0.5,
    fontSize: 24, color: "00EEFF", bold: true,
    fontFace: "Arial"
  });
  
  const contentText = deliverable.content || "";
  const lines = contentText.split('\\n').filter((l: string) => l.trim().length > 0)
    .map((line: string) => {
      const isBullet = line.trim().startsWith('-') || line.trim().startsWith('*');
      return {
        text: line.replace(/^[-*#\\s]+/, '').trim(),
        options: { 
          bullet: isBullet, 
          color: "F8FAFC", 
          fontSize: 14, 
          fontFace: "Arial",
          breakLine: true,
          indentLevel: isBullet ? 1 : 0
        }
      };
    });
    
  slide2.addText(lines.slice(0, 10) as any, { 
    x: 0.5, y: 1.2, w: 9, h: 4,
    valign: "top", align: "left"
  });

  const data = await pres.write({ outputType: "uint8array" }) as Uint8Array;
  return data;
}

async function generatePDF(deliverable: any): Promise<Uint8Array> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // PAGE 1: COVER
  doc.setFillColor(15, 23, 42); // Dark slate background
  doc.rect(0, 0, pageWidth, pageHeight, "F");
  
  // Accent line
  doc.setFillColor(0, 238, 255); // Cyan
  doc.rect(0, 0, pageWidth, 4, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(36);
  doc.setFont("helvetica", "bold");
  
  const titleLines = doc.splitTextToSize(deliverable.name, pageWidth - 40);
  doc.text(titleLines, 20, 100);
  
  doc.setFontSize(14);
  doc.setTextColor(148, 163, 184); // Slate 400
  doc.setFont("helvetica", "normal");
  doc.text("Generated by ExecuAI Autonomous Agent Swarm", 20, 100 + (titleLines.length * 15) + 10);
  
  doc.setFontSize(10);
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 20, pageHeight - 30);
  
  // Logo placeholder
  doc.setDrawColor(0, 238, 255);
  doc.setLineWidth(1);
  doc.circle(pageWidth - 30, pageHeight - 32, 8, "S");
  doc.setFontSize(8);
  doc.setTextColor(0, 238, 255);
  doc.text("AI", pageWidth - 32, pageHeight - 30);

  // PAGE 2: CONTENT
  doc.addPage();
  doc.setFillColor(248, 250, 252); // Off white
  doc.rect(0, 0, pageWidth, pageHeight, "F");
  
  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("EXECUTIVE REPORT", 20, 20);
  
  // Main Content
  doc.setTextColor(51, 65, 85); // Slate 700
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  
  const contentText = deliverable.content || "";
  const paragraphs = contentText.split('\\n\\n');
  
  let y = 50;
  for (const para of paragraphs) {
    if (para.trim() === "") continue;
    
    // Check if it's a header
    if (para.startsWith("##") || para.startsWith("#")) {
       const headerText = para.replace(/#/g, "").trim();
       doc.setFont("helvetica", "bold");
       doc.setFontSize(14);
       doc.setTextColor(15, 23, 42);
       
       if (y > pageHeight - 40) {
         doc.addPage();
         y = 30;
       }
       
       doc.text(headerText, 20, y);
       y += 10;
       continue;
    }
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(51, 65, 85);
    
    const lines = doc.splitTextToSize(para, pageWidth - 40);
    
    if (y + (lines.length * 5) > pageHeight - 20) {
      doc.addPage();
      y = 30;
    }
    
    doc.text(lines, 20, y);
    y += (lines.length * 5.5) + 5;
  }
  
  // Footer on all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    if (i !== 1) { // Skip cover
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`ExecuAI Generated Artifact  |  Page ${i} of ${totalPages}`, 20, pageHeight - 15);
      
      doc.setFillColor(0, 238, 255);
      doc.circle(pageWidth - 20, 15, 3, "F");
    }
  }

  const arrayBuffer = doc.output("arraybuffer");
  return new Uint8Array(arrayBuffer);
}

async function generateCodebaseZip(deliverable: any): Promise<Uint8Array> {
  const zip = new JSZip();
  const name = deliverable.name || "project";
  
  // 1. Root Files
  zip.file("README.md", `# ${name}\n\nGenerated by ExecuAI\n\n${deliverable.content}`);
  zip.file("package.json", JSON.stringify({
    name: name.toLowerCase().replace(/\s+/g, '-'),
    version: "1.0.0",
    dependencies: { "express": "^4.18.2", "cors": "^2.8.5" }
  }, null, 2));
  zip.file(".gitignore", "node_modules\n.env\ndist");

  // 2. Source Code
  const src = zip.folder("src");
  src?.file("index.js", `const express = require('express');\nconst app = express();\n\napp.get('/', (req, res) => res.json({ status: 'ok', project: '${name}' }));\n\napp.listen(3000, () => console.log('Server running on 3000'));`);
  
  // 3. SDLC Documents Folder
  const docs = zip.folder("docs");
  docs?.file("REQUIREMENTS.md", `## Requirements for ${name}\n\n1. Initial Launch\n2. User Auth\n3. Scalability`);
  docs?.file("ARCHITECTURE.md", `## Architecture Design\n\n- Frontend: React\n- Backend: Node.js\n- Database: Hedera Managed`);
  docs?.file("TEST_PLAN.md", `## Test Strategy\n\n- Unit Testing\n- Integration Testing\n- User Acceptance`);

  const zipBuffer = await zip.generateAsync({ type: "uint8array" });
  return zipBuffer;
}

// ... helper functions for other types (keeping them simple for brevity but using better headers)
async function generateImage(deliverable: any): Promise<Uint8Array> {
  return new TextEncoder().encode(`<svg width="1200" height="630" viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
    <rect width="1200" height="630" fill="#0A0A0A"/>
    <text x="600" y="300" text-anchor="middle" font-family="Arial" font-size="48" fill="#00EEFF">${deliverable.name}</text>
  </svg>`);
}

async function generateDocument(deliverable: any): Promise<Uint8Array> {
  return new TextEncoder().encode(`<w:wordDocument xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>${deliverable.content}</w:t></w:r></w:p></w:body></w:wordDocument>`);
}

async function generateSpreadsheet(deliverable: any): Promise<Uint8Array> {
  return new TextEncoder().encode(`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row><c><v>Item</v></c><c><v>Quantity</v></c><c><v>Cost</v></c></row><row><c><v>Infrastructure</v></c><c><v>1</v></c><c><v>500</v></c></row></sheetData></worksheet>`);
}

function parseCodebaseFiles(content: string, name: string = "project"): Array<{path: string, content: string | Uint8Array}> {
    return [
        { path: "README.md", content: `# ${name}\n\n${content}` },
        { path: "src/index.js", content: `console.log("Hello from ${name}");` }
    ];
}
